[package]
name = "todo_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
serde ={ version = "*",features = ["derive"]}
serde_json ="1.0"
clap = { version = "4.5", features = ["derive"] }
colored = "2.0"